### ISSUE TITLE
0.0.4 version of gem has broken things

### ISSUE THREAD

**Issue by rossfuhrman** [rossfuhrman/starting_blocks-rspec#5]
It appears that the 0.0.4 version of the gem has broken the integration with the blinky plugin as well as the watch plugin. I have not tested the stopplicht or growl plugins.

**Comment by darrencauthon** [comment]
I just uninstalled and reinstalled it, and it's working fine for me. 0.0.4.  I'm staring at a green blinky light now.

What specifically are you experiencing?

**Comment by rossfuhrman** [comment]
The blinky light always turns green at the end of the tests whether my tests passed or not.

**Comment by darrencauthon** [comment]
Which tests are you running?  Is it a something for your company, or is it something that’s public?

When I did my own tests, I ran them on this public project:  https://github.com/crmckenzie/richmond

—

**Comment by rossfuhrman** [comment]
Hmmm. I had tried it on two of my projects which aren't public and got the same result where it was always green.
However, it is behaving as expected when running the tests for richmond. I will dig a bit deeper to see what the difference is.

**Comment by rossfuhrman** [comment]
Fixed the issue in this commit:
https://github.com/rossfuhrman/starting_blocks-rspec/commit/21870dc094bf4d0ed979f1f7f8516971c2c44d70

Handle singular and plural forms of test results.
In the rspec results, both example and failure are correctly pluralized.
This was causing a problem with the parsing of the results as it was
expecting example and failure to always be plural.

**Comment by rossfuhrman** [comment]
This fix is in the 0.0.5 version of the gem.
